# Generated by Django 4.1.2 on 2022-11-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fechaAlta', models.DateTimeField(verbose_name='Fecha Alta')),
                ('correo', models.CharField(max_length=150, null=True)),
                ('movil', models.CharField(max_length=14, null=True)),
            ],
        ),
    ]
